### PR TITLE
Fixed updated library conflicts for MacOS X. Moved to Python3.

### PR DESCRIPTION
**Pull request by giansegato**
- Fully moved to Python3
- Fixed COCOA-PyobjC wrong integration
- Fixed wrongful self-kill of MacOS X client
- Fixed SQLAlchemy inconsistency data types with the new library version
- Merge pull request #1 from jimmyyentran/master
- Merge pull request #2 from xamogast/master

### CODE REVIEW

**Comment by daroczig** [comment]
this is awesome, thanks a lot @giansegato 

do you plan to maintain the py3 version?
I'm still using the py2 version, but as it's going away and gets more and more troublesome to keep installed on Arch, I'm really thinking about switching to your branch

**Comment by giansegato** [comment]
> this is awesome, thanks a lot @giansegato
> 
> do you plan to maintain the py3 version?
> I'm still using the py2 version, but as it's going away and gets more and more troublesome to keep installed on Arch, I'm really thinking about switching to your branch

Hi @daroczig! As far as I know, my branch should be stable for MacOS users running Python 3. I haven't tested Linux, so I cannot grant for the OS idiosyncrasies, but the Python layer should work pretty well.

I hoped for a merge in develop / master (the current main branch is _not_ working anymore), but it looks that the maintainer is no longer active on the project.

**Comment by daroczig** [comment]
Thanks again for the prompt reply, I will give this a try :+1:

I was actually thinking about migrating to an alternative tracker seeing that the project is not being maintained anymore, but if I can get it working with Python 3 -- then I'm good for a while :)

**Comment by daroczig** [comment]
I've just installed in a  virtual env and seems to work great in most cases :tada: 

One interesting issue I run into: `selfstats` does not report the duration correctly.

See eg this with `master`:

```
$ selfstats --date "2020 05 08" --clock "00:00" --limit 1m
<RowID> <Starting date and time> <Duration> <Process> <Window title> <Number of keys pressed>
1736324 2020-05-07 23:59:59.207359 6s Emacs "..." 1
1736325 2020-05-08 00:00:05.628195 3s Gnome-terminal "..." 5
```

And the python 3 fork:

```
$ /virtualenv/path/selfstats --date "2020 05 08" --clock "00:00" --limit 1m
<RowID> <Starting date and time> <Duration> <Process> <Window title> <Number of keys pressed>
1736324 2020-05-07 23:59:59.207359 0 days, 0h 0m 0s Emacs "..." 1
1736325 2020-05-08 00:00:05.628195 0 days, 0h 0m 0s Gnome-terminal "..." 5
```

Something might be off with `timedelta`?

**Comment by dumblob** [comment]
Anyone found a fix for the timedelta issue?

**Pull request closed without merging**
